import {
  Dumbbell,
  PartyPopper,
  Palette,
  Music,
  BookOpen,
  Trophy,
  Baby,
  Users,
  Trash2,
  ShieldAlert,
  Trees,
  Volleyball,
  Stethoscope,
  ShoppingCart,
  Landmark,
  MapPinned,
  Briefcase,
  Sprout,
  Megaphone,
  Store,
  Repeat,
  Search,
  Images,
  Lightbulb,
  DoorOpen,
  Mailbox,
  Info,
  Phone,
  Settings,
  Utensils,
  Scissors,
  GraduationCap,
  Home,
  Wrench,
  ScrollText,
  Accessibility,
  Lock,
  type LucideIcon,
} from "lucide-react";

/**
 * מיפוי מחרוזת→אייקון. נשמר בבסיס הנתונים כ-`icon_key` (טקסט), לא כרכיב React —
 * הדמו המקורי שמר רכיב React בתוך "נתונים", מה שחסם שמירה אמיתית ב-DB.
 */
export const ICONS: Record<string, LucideIcon> = {
  dumbbell: Dumbbell,
  party: PartyPopper,
  palette: Palette,
  music: Music,
  book: BookOpen,
  trophy: Trophy,
  baby: Baby,
  users: Users,
  trash: Trash2,
  shield: ShieldAlert,
  trees: Trees,
  ball: Volleyball,
  health: Stethoscope,
  grocery: ShoppingCart,
  landmark: Landmark,
  map: MapPinned,
  job: Briefcase,
  land: Sprout,
  megaphone: Megaphone,
  store: Store,
  secondhand: Repeat,
  lostfound: Search,
  gallery: Images,
  idea: Lightbulb,
  gate: DoorOpen,
  mailbox: Mailbox,
  info: Info,
  phone: Phone,
  settings: Settings,
  food: Utensils,
  beauty: Scissors,
  education: GraduationCap,
  home: Home,
  services: Wrench,
  scroll: ScrollText,
  accessibility: Accessibility,
  lock: Lock,
};

export function getIcon(key: string | null | undefined): LucideIcon {
  return (key && ICONS[key]) || Info;
}
